### PR TITLE
maven requires JAVA_HOME being set

### PR DESCRIPTION
**Pull request by joslynesser**
@jkutner I ran into this when attempting to run this buildpack within https://github.com/heroku/stack-images/tree/master/heroku-18-build

I noticed the cloud native buildpack had a note about something similar: https://github.com/heroku/java-buildpack/blob/58b1b157d0322da10981ecf6abe11069896cfd06/bin/build#L37-L39

Think this the right place for the fix? Saw that the `heroku/jvm-common` buildpack sets it in https://github.com/heroku/heroku-buildpack-jvm-common/blob/4d7c3f40d352d5a5090091d026017da18c2ede28/bin/java#L70-L71 in order to install the jdk, but it is also needed for maven execution here in `heroku/java`.

## steps to reproduce

With a `bin/test-compile` in `$PWD` for an example java application that looks like the following:
```
buildDir=$1
cacheDir=$2
envDir=$3

tmpdir=$(mktemp -d)

curl --silent --location https://github.com/heroku/heroku-buildpack-java/archive/master.tar.gz | tar xzm -C $tmpdir --strip-components=1

${tmpdir}/bin/test-compile $1 $2 $3
```

Running `bin/test-compile` within `heroku/heroku:18-build` while having `$PWD` mounted to `/app` results in:
```
$ docker run --rm -v $PWD:/app heroku/heroku:18-build /bin/bash -c "/app/bin/test-compile /app /app"
-----> Using provided JDK
-----> Executing: ./mvnw clean dependency:resolve-plugins test-compile
Error: JAVA_HOME is not defined correctly.
  We cannot execute 

 !     ERROR: Failed to build app with Maven
       We're sorry this build is failing! If you can't find the issue in application code,
       please submit a ticket so we can help: https://help.heroku.com/
```

## after fix
```
$ docker run --rm -v $PWD:/app heroku/heroku:18-build /bin/bash -c "/app/bin/test-compile /app /app"
-----> Using provided JDK
-----> Executing: ./mvnw clean dependency:resolve-plugins test-compile
       [INFO] Scanning for projects...
       [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.2.RELEASE/spring-boot-starter-parent-2.1.2.RELEASE.pom
...
       [INFO] BUILD SUCCESS
       [INFO] ------------------------------------------------------------------------
       [INFO] Total time:  02:05 min
       [INFO] Finished at: 2019-05-01T23:10:52Z
       [INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by jkutner** [comment]
@joslynesser the comment in the CNB is a bit misleading because I mean "a JVM CNB, which doesn't exist yet, should handle this". In fact, the Heroku [jvm-common buildpack]() should be doing this when `install_java` is invoked:
https://github.com/heroku/heroku-buildpack-jvm-common/blob/master/bin/java#L70-L71

So I'm not sure why this isn't working in the first place.

Are you using `docker run` to reproduce what you're seeing on Heroku CI, or is `docker run` you're target environment?

**Comment by joslynesser** [comment]
`docker run` is the target environment. We're attempting to replicate what Heroku's build/CI systems are performing with as much parity as we can, as we're required to build slugs in an isolated network and push via the Platform API.

`JAVA_HOME` is set for `install_java`, but it is not set for the subsequent `run_mvn`. `/bin/compile` executes both in https://github.com/heroku/heroku-buildpack-java/blob/master/bin/compile#L20 + https://github.com/heroku/heroku-buildpack-java/blob/master/bin/compile#L25

The test suite sets up the requirement in https://github.com/heroku/heroku-buildpack-java/blob/master/test/compile_test.sh#L17-L22, which is why tests don't see the error.

Here's another example with a `Dockerfile` that experiences the error:
```
FROM heroku/heroku:18-build AS build
ENV HOME /app
WORKDIR /app
RUN mkdir -p /buildpacks/java && \
    mkdir -p /tmp/cache && \
    curl --silent --location https://github.com/heroku/heroku-buildpack-java/archive/master.tar.gz | tar xzm -C /buildpacks/java --strip-components=1
COPY . /app
RUN /buildpacks/java/bin/compile /app /tmp/cache
```

Executing the above results in:
```
$ docker build -t service-example-build --target=build .
Step 1/7 : FROM heroku/heroku:18-build AS build
 ---> 0213f6074e19
Step 2/7 : ENV HOME /app
 ---> Using cache
 ---> 6ac1f5ae3308
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> 630e4688d795
Step 4/7 : RUN mkdir -p /buildpacks/java &&     mkdir -p /tmp/cache &&     curl --silent --location https://github.com/heroku/heroku-buildpack-java/archive/master.tar.gz | tar xzm -C /buildpacks/java --strip-components=1
 ---> Using cache
 ---> df3e9be23262
Step 5/7 : COPY . /app
 ---> Using cache
 ---> d02fd5d02cd1
Step 6/7 : RUN /buildpacks/java/bin/compile /app /tmp/cache
 ---> Running in 43ea8f530ecb
-----> Using provided JDK
-----> Executing: ./mvnw -DskipTests clean dependency:list install
Error: JAVA_HOME is not defined correctly.
  We cannot execute 

 !     ERROR: Failed to build app with Maven
       We're sorry this build is failing! If you can't find the issue in application code,
       please submit a ticket so we can help: https://help.heroku.com/
```

Installing java succeeds, while compiling with maven fails.

**Comment by jkutner** [comment]
Using that `Dockerfile` I wasn't able to reproduce to the problem. But I noticed you have this:

```
-----> Using provided JDK
```

Where is that provided JDK coming from? Is there a `.jdk` directory in your app? If so, the `JAVA_HOME` that is set by the buildpack may be malformed.

The `export JAVA_HOME` in the jvm-common buildpack will (should?) ensure that the env var is set for the rest of the bash execution.

**Comment by joslynesser** [comment]
D'oh, you're completely right @jkutner. I accidentally passed in a previously built `.jdk` in the docker build context when I had previously extracted the `/app` directory to package up a slug from a previous build. Sigh, ignore this issue completely. I'm extremely sorry for not catching that and wasting your time! 🤦‍♂

By having an entry point that sources all files in `.profile.d`, I can now run something like the following to emulate a Heroku CI test run after the `build` image is created and `/bin/compile` has been called:
```
docker run --rm service-example-build /bin/bash -c '/buildpacks/java/bin/test /app'
```

Onward and upward! Sorry again @jkutner

**Pull request closed without merging**
