### PR TITLE
Add support for Maven Polyglot POM formats

### PR DESCRIPTION
**Pull request by ecopoesis**

### CODE REVIEW

**Comment by jkutner** [comment]
I'll take a look at this change this week. I think it's something we can reasonably support. But there are a few things we (Heroku) have to consider before official adopting support like this. We repeat the buildpacks detection logic in a few places internally to enable various platform features for Java apps, and we'd have to replicate this change in those places (unfortunately).

In the meantime, it would be helpful if you could modify an app like https://github.com/kissaten/java-minimal to include a `pom.yaml` or similar for testing.

Thanks!

**Comment by ecopoesis** [comment]
I've create a fork of `java-minimal` that uses the YAML POM format: https://github.com/ecopoesis/java-minimal

**Comment by jkutner** [comment]
I'm thinking that I may merge this but leave it undocumented (at least for the time being). That would mean the buildpack would work, but a few Heroku features (such as JVM Language Metrics) might not work without some manual setup steps. Will decide for sure this week.

**Comment by jkutner** [comment]
I'm merging this PR into #86 and closing this PR so I can add an integration test, and run those tests on CI (they won't run from a forked PR because they require an API key).

**Pull request closed without merging**
